#!/bin/bash
# Deploy using Docker Hub + Render auto-deploy (no API key needed)

echo "🚀 Alternative Deployment Method"
echo "================================"
echo ""
echo "Since we don't have Render API key, use this method:"
echo ""
echo "METHOD 1: Use Render Dashboard (Easiest)"
echo "1. Go to: https://dashboard.render.com/"
echo "2. Click 'New +' → 'Blueprint'"
echo "3. Connect: paxni12345-web/agent-cli"
echo "4. Render detects render.yaml automatically"
echo "5. Set ANTHROPIC_API_KEY"
echo "6. Click 'Apply'"
echo "7. Done in 5 minutes!"
echo ""
echo "METHOD 2: Railway (Alternative)"
echo "1. Go to: https://railway.app/"
echo "2. 'New Project' → 'Deploy from GitHub repo'"
echo "3. Select: paxni12345-web/agent-cli"
echo "4. Railway auto-deploys from Dockerfile"
echo "5. Add ANTHROPIC_API_KEY in Variables"
echo "6. Done!"
echo ""
echo "METHOD 3: Vercel (For static sites)"
echo "1. Go to: https://vercel.com/"
echo "2. 'Add New' → 'Project'"
echo "3. Import: paxni12345-web/agent-cli"
echo "4. Deploy public/ directory"
echo ""
echo "✅ All methods are FREE tier available!"
