#!/bin/bash
# Simple Render deployment via GitHub integration

echo "🚀 Agent CLI - Render Deployment Helper"
echo ""
echo "Since Render requires authentication, please follow these steps:"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 STEP 1: Go to Render Dashboard"
echo "════════════════════════════════════════════════════════════════"
echo "   https://dashboard.render.com/"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 STEP 2: Create New Service"
echo "════════════════════════════════════════════════════════════════"
echo "   1. Click 'New +' → 'Blueprint'"
echo "   2. Connect GitHub repo: paxni12345-web/agent-cli"
echo "   3. Render will detect render.yaml automatically"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 STEP 3: Set Environment Variables"
echo "════════════════════════════════════════════════════════════════"
echo "   Required:"
echo "   - ANTHROPIC_API_KEY = (your Anthropic key)"
echo ""
echo "   Optional:"
echo "   - OPENAI_API_KEY = (your OpenAI key)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 STEP 4: Deploy!"
echo "════════════════════════════════════════════════════════════════"
echo "   Click 'Apply' and wait ~5 minutes"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ Your app will be live at:"
echo "════════════════════════════════════════════════════════════════"
echo "   https://agent-cli-xxxx.onrender.com"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📝 Alternative: Use Render API (if you have API key)"
echo "════════════════════════════════════════════════════════════════"
echo "   export RENDER_API_KEY='your_key_here'"
echo "   ./deploy-render-api.sh"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📚 Full documentation: DEPLOYMENT.md"
echo "════════════════════════════════════════════════════════════════"
