/**
 * Security Test Suite: Session Hijacking
 * Tests for session fixation, session theft, and session management vulnerabilities
 */

import { SecurityManager, LoginContext, Session } from '../../../src/security/SecurityManager';
import * as crypto from 'crypto';

describe('Session Hijacking Security Tests', () => {
  let securityManager: SecurityManager;
  let testContext: LoginContext;
  const validPassword = 'ValidPass123!';

  beforeEach(() => {
    securityManager = new SecurityManager({
      enableAuth: true,
      enableAudit: true,
      jwtSecret: 'test-secret-key-for-session-tests',
      sessionTimeout: 1800000, // 30 minutes
      jwtExpiry: 3600, // 1 hour
      redisUrl: 'redis://localhost:6379',
    });

    testContext = {
      ipAddress: '192.168.1.100',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0',
      deviceId: 'test-device-001',
    };
  });

  afterEach(async () => {
    await securityManager.disconnect();
  });

  describe('Session Fixation Attacks', () => {
    test('should regenerate session ID after login', async () => {
      const user = await securityManager.createUser(
        'fixationuser',
        'fixation@example.com',
        validPassword,
        ['user']
      );

      // Login should create new session
      const { sessionId: sessionId1 } = await securityManager.login(
        'fixationuser',
        validPassword,
        testContext
      );

      // Logout and login again
      const sessions1 = await securityManager.getUserSessions(user.id);
      expect(sessions1.some(s => s.id === sessionId1)).toBe(true);

      // Second login should create different session
      const { sessionId: sessionId2 } = await securityManager.login(
        'fixationuser',
        validPassword,
        { ...testContext, deviceId: 'device-002' }
      );

      expect(sessionId1).not.toBe(sessionId2);
    });

    test('should not accept pre-set session IDs', async () => {
      const user = await securityManager.createUser(
        'presetuser',
        'preset@example.com',
        validPassword,
        ['user']
      );

      // Attacker tries to set session ID before login
      const attackerSessionId = 'attacker-controlled-session-id';

      const { sessionId } = await securityManager.login(
        'presetuser',
        validPassword,
        testContext
      );

      // Session ID should be generated by server, not accepted from client
      expect(sessionId).not.toBe(attackerSessionId);
      expect(sessionId).toMatch(/^sec-/);
    });

    test('should invalidate old session on new login', async () => {
      const user = await securityManager.createUser(
        'invalidateuser',
        'invalidate@example.com',
        validPassword,
        ['user']
      );

      const { token: token1, sessionId: sessionId1 } = await securityManager.login(
        'invalidateuser',
        validPassword,
        testContext
      );

      // Login again from different device
      const { token: token2, sessionId: sessionId2 } = await securityManager.login(
        'invalidateuser',
        validPassword,
        { ...testContext, deviceId: 'device-002' }
      );

      // Both sessions should be valid (multi-device support)
      const validatedUser1 = await securityManager.validateToken(token1);
      const validatedUser2 = await securityManager.validateToken(token2);

      expect(validatedUser1).toBeDefined();
      expect(validatedUser2).toBeDefined();
      expect(sessionId1).not.toBe(sessionId2);
    });

    test('should use unpredictable session IDs', async () => {
      const user = await securityManager.createUser(
        'unpredictuser',
        'unpredict@example.com',
        validPassword,
        ['user']
      );

      const sessionIds: string[] = [];

      for (let i = 0; i < 10; i++) {
        const { sessionId } = await securityManager.login(
          'unpredictuser',
          validPassword,
          { ...testContext, deviceId: `device-${i}` }
        );
        sessionIds.push(sessionId);
      }

      // All session IDs should be unique and unpredictable
      const uniqueIds = new Set(sessionIds);
      expect(uniqueIds.size).toBe(10);

      // Check for sequential patterns
      const areSequential = sessionIds.every((id, index) => {
        if (index === 0) return true;
        const prevNum = parseInt(sessionIds[index - 1].split('-')[1]);
        const currNum = parseInt(id.split('-')[1]);
        return !isNaN(prevNum) && !isNaN(currNum) && currNum !== prevNum + 1;
      });

      expect(areSequential).toBe(true);
    });
  });

  describe('Session Theft via XSS', () => {
    test('should mark tokens as HttpOnly (not accessible via JS)', async () => {
      const user = await securityManager.createUser(
        'xsstheftuser',
        'xsstheft@example.com',
        validPassword,
        ['user']
      );

      const { token } = await securityManager.login(
        'xsstheftuser',
        validPassword,
        testContext
      );

      // In production, token should be stored in HttpOnly cookie
      expect(token).toBeDefined();
      expect(typeof token).toBe('string');
    });

    test('should implement Secure flag for cookies', async () => {
      // Cookies should only be sent over HTTPS
      const cookieOptions = {
        httpOnly: true,
        secure: true, // Only send over HTTPS
        sameSite: 'strict' as const,
      };

      expect(cookieOptions.httpOnly).toBe(true);
      expect(cookieOptions.secure).toBe(true);
      expect(cookieOptions.sameSite).toBe('strict');
    });

    test('should implement SameSite attribute', () => {
      const cookieOptions = {
        sameSite: 'strict' as const, // Prevent CSRF
      };

      expect(cookieOptions.sameSite).toBe('strict');
    });

    test('should not expose session tokens in URLs', async () => {
      const user = await securityManager.createUser(
        'urltokenuser',
        'urltoken@example.com',
        validPassword,
        ['user']
      );

      const { token } = await securityManager.login(
        'urltokenuser',
        validPassword,
        testContext
      );

      // Token should not be in URL query parameters
      const url = 'https://example.com/dashboard';
      expect(url).not.toContain(token);
      expect(url).not.toContain('token=');
    });
  });

  describe('Session Theft via Network Sniffing', () => {
    test('should track session IP address', async () => {
      const user = await securityManager.createUser(
        'iptrackuser',
        'iptrack@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'iptrackuser',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);

      expect(session).toBeDefined();
      expect(session?.ipAddress).toBe(testContext.ipAddress);
    });

    test('should detect IP address changes', async () => {
      const user = await securityManager.createUser(
        'ipchangeuser',
        'ipchange@example.com',
        validPassword,
        ['user']
      );

      const { token, sessionId } = await securityManager.login(
        'ipchangeuser',
        validPassword,
        testContext
      );

      // Validate token from same IP
      const validatedUser1 = await securityManager.validateToken(token);
      expect(validatedUser1).toBeDefined();

      // In production, should detect IP change and potentially require re-authentication
      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);
      expect(session?.ipAddress).toBe(testContext.ipAddress);
    });

    test('should track user agent changes', async () => {
      const user = await securityManager.createUser(
        'uatrackuser',
        'uatrack@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'uatrackuser',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);

      expect(session?.userAgent).toBe(testContext.userAgent);
    });

    test('should enforce HTTPS for all authenticated requests', () => {
      const secureUrl = 'https://example.com/api';
      const insecureUrl = 'http://example.com/api';

      expect(secureUrl.startsWith('https://')).toBe(true);
      expect(insecureUrl.startsWith('https://')).toBe(false);
    });
  });

  describe('Session Timeout and Expiration', () => {
    test('should expire sessions after inactivity', async () => {
      const shortTimeoutManager = new SecurityManager({
        enableAuth: true,
        jwtSecret: 'test-secret',
        sessionTimeout: 100, // 100ms for testing
        jwtExpiry: 1, // 1 second
        redisUrl: 'redis://localhost:6379',
      });

      const user = await shortTimeoutManager.createUser(
        'timeoutuser',
        'timeout@example.com',
        validPassword,
        ['user']
      );

      const { token } = await shortTimeoutManager.login(
        'timeoutuser',
        validPassword,
        testContext
      );

      // Wait for session to timeout
      await new Promise(resolve => setTimeout(resolve, 150));

      const result = await shortTimeoutManager.validateToken(token);
      expect(result).toBeNull();

      await shortTimeoutManager.disconnect();
    });

    test('should enforce absolute session timeout', async () => {
      const user = await securityManager.createUser(
        'absoluteuser',
        'absolute@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'absoluteuser',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);

      expect(session).toBeDefined();
      expect(session?.expiresAt).toBeGreaterThan(Date.now());
    });

    test('should update last activity on each request', async () => {
      const user = await securityManager.createUser(
        'activityuser',
        'activity@example.com',
        validPassword,
        ['user']
      );

      const { token, sessionId } = await securityManager.login(
        'activityuser',
        validPassword,
        testContext
      );

      const sessions1 = await securityManager.getUserSessions(user.id);
      const session1 = sessions1.find(s => s.id === sessionId);
      const lastActivity1 = session1?.lastActivity;

      await new Promise(resolve => setTimeout(resolve, 10));

      // Validate token (simulates request)
      await securityManager.validateToken(token);

      const sessions2 = await securityManager.getUserSessions(user.id);
      const session2 = sessions2.find(s => s.id === sessionId);
      const lastActivity2 = session2?.lastActivity;

      expect(lastActivity2).toBeGreaterThanOrEqual(lastActivity1!);
    });

    test('should allow extending session before expiration', async () => {
      const user = await securityManager.createUser(
        'extenduser',
        'extend@example.com',
        validPassword,
        ['user']
      );

      const { token, sessionId } = await securityManager.login(
        'extenduser',
        validPassword,
        testContext
      );

      const sessions1 = await securityManager.getUserSessions(user.id);
      const session1 = sessions1.find(s => s.id === sessionId);
      const expiresAt1 = session1?.expiresAt;

      // Wait a bit
      await new Promise(resolve => setTimeout(resolve, 10));

      // Activity extends session
      await securityManager.validateToken(token);

      const sessions2 = await securityManager.getUserSessions(user.id);
      const session2 = sessions2.find(s => s.id === sessionId);
      const expiresAt2 = session2?.expiresAt;

      // Expiration should be the same or extended
      expect(expiresAt2).toBeGreaterThanOrEqual(expiresAt1!);
    });
  });

  describe('Concurrent Session Management', () => {
    test('should track all active sessions per user', async () => {
      const user = await securityManager.createUser(
        'multisessionuser',
        'multisession@example.com',
        validPassword,
        ['user']
      );

      // Create multiple sessions
      const session1 = await securityManager.login(
        'multisessionuser',
        validPassword,
        { ...testContext, deviceId: 'device-1' }
      );

      const session2 = await securityManager.login(
        'multisessionuser',
        validPassword,
        { ...testContext, deviceId: 'device-2' }
      );

      const session3 = await securityManager.login(
        'multisessionuser',
        validPassword,
        { ...testContext, deviceId: 'device-3' }
      );

      const sessions = await securityManager.getUserSessions(user.id);
      expect(sessions.length).toBeGreaterThanOrEqual(3);
    });

    test('should allow revoking specific sessions', async () => {
      const user = await securityManager.createUser(
        'revokespecific',
        'revokespecific@example.com',
        validPassword,
        ['user']
      );

      const { token: token1, sessionId: sessionId1 } = await securityManager.login(
        'revokespecific',
        validPassword,
        { ...testContext, deviceId: 'device-1' }
      );

      const { token: token2, sessionId: sessionId2 } = await securityManager.login(
        'revokespecific',
        validPassword,
        { ...testContext, deviceId: 'device-2' }
      );

      // Revoke first session
      await securityManager.revokeSession(sessionId1, testContext);

      const result1 = await securityManager.validateToken(token1);
      const result2 = await securityManager.validateToken(token2);

      expect(result1).toBeNull();
      expect(result2).toBeDefined();
    });

    test('should allow revoking all sessions except current', async () => {
      const user = await securityManager.createUser(
        'revokeothers',
        'revokeothers@example.com',
        validPassword,
        ['user']
      );

      const session1 = await securityManager.login(
        'revokeothers',
        validPassword,
        { ...testContext, deviceId: 'device-1' }
      );

      const session2 = await securityManager.login(
        'revokeothers',
        validPassword,
        { ...testContext, deviceId: 'device-2' }
      );

      const session3 = await securityManager.login(
        'revokeothers',
        validPassword,
        { ...testContext, deviceId: 'device-3' }
      );

      // Revoke all except session2
      const revokedCount = await securityManager.revokeOtherSessions(
        user.id,
        session2.sessionId,
        testContext
      );

      expect(revokedCount).toBeGreaterThanOrEqual(2);

      const result1 = await securityManager.validateToken(session1.token);
      const result2 = await securityManager.validateToken(session2.token);
      const result3 = await securityManager.validateToken(session3.token);

      expect(result1).toBeNull();
      expect(result2).toBeDefined();
      expect(result3).toBeNull();
    });

    test('should revoke all sessions on password change', async () => {
      const user = await securityManager.createUser(
        'passwordchange',
        'passwordchange@example.com',
        validPassword,
        ['user']
      );

      const { token } = await securityManager.login(
        'passwordchange',
        validPassword,
        testContext
      );

      // Change password
      await securityManager.changePassword(
        user.id,
        validPassword,
        'NewPassword123!',
        testContext
      );

      // Old token should be invalid
      const result = await securityManager.validateToken(token);
      expect(result).toBeNull();
    });
  });

  describe('Device Fingerprinting', () => {
    test('should generate consistent device IDs', async () => {
      const deviceId1 = crypto
        .createHash('sha256')
        .update(testContext.ipAddress + ':' + testContext.userAgent)
        .digest('hex')
        .substring(0, 16);

      const deviceId2 = crypto
        .createHash('sha256')
        .update(testContext.ipAddress + ':' + testContext.userAgent)
        .digest('hex')
        .substring(0, 16);

      expect(deviceId1).toBe(deviceId2);
    });

    test('should detect device changes', async () => {
      const user = await securityManager.createUser(
        'devicechange',
        'devicechange@example.com',
        validPassword,
        ['user']
      );

      const { sessionId: sessionId1 } = await securityManager.login(
        'devicechange',
        validPassword,
        { ...testContext, deviceId: 'device-1' }
      );

      const { sessionId: sessionId2 } = await securityManager.login(
        'devicechange',
        validPassword,
        { ...testContext, deviceId: 'device-2' }
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session1 = sessions.find(s => s.id === sessionId1);
      const session2 = sessions.find(s => s.id === sessionId2);

      expect(session1?.deviceId).toBe('device-1');
      expect(session2?.deviceId).toBe('device-2');
      expect(session1?.deviceId).not.toBe(session2?.deviceId);
    });

    test('should store device fingerprint details', async () => {
      const user = await securityManager.createUser(
        'fingerprint',
        'fingerprint@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'fingerprint',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);

      expect(session).toBeDefined();
      expect(session?.deviceId).toBeDefined();
      expect(session?.userAgent).toBe(testContext.userAgent);
      expect(session?.ipAddress).toBe(testContext.ipAddress);
    });
  });

  describe('Session Storage Security', () => {
    test('should not store sensitive data in sessions', async () => {
      const user = await securityManager.createUser(
        'sensitivesession',
        'sensitive@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'sensitivesession',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      const session = sessions.find(s => s.id === sessionId);

      // Session should not contain password or sensitive user data
      expect(JSON.stringify(session)).not.toContain(validPassword);
      expect(JSON.stringify(session)).not.toContain('passwordHash');
    });

    test('should encrypt session data at rest', async () => {
      const user = await securityManager.createUser(
        'encryptsession',
        'encryptsession@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'encryptsession',
        validPassword,
        testContext
      );

      // Sessions stored in Redis should be serialized
      // In production, they should also be encrypted
      expect(sessionId).toBeDefined();
      expect(sessionId).toMatch(/^sec-/);
    });

    test('should use secure session storage backend', async () => {
      // Redis is being used for session storage
      const user = await securityManager.createUser(
        'redissession',
        'redis@example.com',
        validPassword,
        ['user']
      );

      const { sessionId } = await securityManager.login(
        'redissession',
        validPassword,
        testContext
      );

      const sessions = await securityManager.getUserSessions(user.id);
      expect(sessions.length).toBeGreaterThan(0);
    });
  });

  describe('Session Hijacking Detection', () => {
    test('should log suspicious session activity', async () => {
      const user = await securityManager.createUser(
        'suspicious',
        'suspicious@example.com',
        validPassword,
        ['user']
      );

      const { token } = await securityManager.login(
        'suspicious',
        validPassword,
        testContext
      );

      // Validate from same context
      await securityManager.validateToken(token);

      // Check audit logs
      const logs = await securityManager.getAuditLogs({
        userId: user.id,
        action: 'auth:login',
      });

      expect(logs.length).toBeGreaterThan(0);
      expect(logs[0].ipAddress).toBe(testContext.ipAddress);
    });

    test('should detect rapid session creation', async () => {
      const user = await securityManager.createUser(
        'rapidcreate',
        'rapid@example.com',
        validPassword,
        ['user']
      );

      const startTime = Date.now();
      const sessions = [];

      for (let i = 0; i < 5; i++) {
        const session = await securityManager.login(
          'rapidcreate',
          validPassword,
          { ...testContext, deviceId: `device-${i}` }
        );
        sessions.push(session);
      }

      const endTime = Date.now();
      const duration = endTime - startTime;

      // Multiple sessions created quickly could be suspicious
      expect(sessions.length).toBe(5);
      expect(duration).toBeDefined();
    });

    test('should alert on session from unusual location', async () => {
      const user = await securityManager.createUser(
        'unusualloc',
        'unusual@example.com',
        validPassword,
        ['user']
      );

      // Normal login from usual location
      await securityManager.login('unusualloc', validPassword, testContext);

      // Login from unusual location
      const unusualContext: LoginContext = {
        ipAddress: '1.2.3.4',
        userAgent: 'Different User Agent',
        deviceId: 'new-device',
      };

      const { sessionId } = await securityManager.login(
        'unusualloc',
        validPassword,
        unusualContext
      );

      const logs = await securityManager.getAuditLogs({
        userId: user.id,
        action: 'auth:login',
      });

      // Should log both logins with different IPs
      const ips = logs.map(log => log.ipAddress);
      expect(ips).toContain(testContext.ipAddress);
      expect(ips).toContain(unusualContext.ipAddress);
    });
  });
});
